use meta_signal_message::{
    META_MESSAGE_INTERFACE_RUST, META_MESSAGE_INTERFACE_SOURCE, bootstrap_manifest,
};

#[test]
fn canonical_source_imports_exact_producer_identity_and_keeps_roles_empty() {
    assert!(
        META_MESSAGE_INTERFACE_SOURCE
            .starts_with("Interface.{1 0 0}\n[signal_message:lib.[MessageDaemonConfiguration]]")
    );
    assert!(META_MESSAGE_INTERFACE_SOURCE.contains("OwnerRequest.["));
    assert!(META_MESSAGE_INTERFACE_SOURCE.contains("OwnerReply.["));
    assert!(META_MESSAGE_INTERFACE_SOURCE.contains("\n  []\n  []\n  []\n  ["));
}

#[test]
fn strict_projection_uses_encoded_local_and_imported_coordinates() {
    assert!(META_MESSAGE_INTERFACE_RUST.starts_with(
        "// @generated by schema-rust from an authority-verified bootstrap Interface"
    ));
    assert!(META_MESSAGE_INTERFACE_RUST.contains("signal_message::schema::lib::z2VL2C"));
    for visible in ["OwnerRequest", "OwnerReply", "ConfigurationGeneration"] {
        assert!(!META_MESSAGE_INTERFACE_RUST.contains(&format!("pub struct {visible}")));
        assert!(!META_MESSAGE_INTERFACE_RUST.contains(&format!("pub enum {visible}")));
    }
    assert_eq!(bootstrap_manifest::DECLARATION_SEATS.len(), 23);
}

#[test]
fn historical_source_directory_is_absent() {
    let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR"));
    assert!(!root.join("schema").exists());
    assert!(root.join("ethos/interface.ethos").is_file());
}
