// @generated by schema-rust from an authority-verified bootstrap Interface

pub struct z2VLUj ( z2VYdt ,) ;
pub enum z2VY5P {z2Vdbu ,} 
pub struct z2VTC7 ( z2VW54 ,) ;
pub struct z2VZEw ( z2VLUj ,) ;
pub enum z2VM7X {z2VKwC , z2VX9E ,} 
pub struct z2VR6z {
    pub field_0: z2VUdf,
    pub field_1: z2VKyZ,
}
pub enum z2Vc2e {
    z2VWNS(signal_message::schema::lib::z2VL2C),
}
pub struct z2VKyZ ( z2VM7X ,) ;
pub struct z2VW54 ( z2VWBb ,) ;
pub enum z2VYLc {z2VcWw ( z2VTC7 ,) , z2VT5g ( z2VZEw ,) , z2Vc4F ( z2VR6z ,) ,} 
pub struct z2VUdf ( z2VY5P ,) ;
pub struct z2VYdt(u64);
impl z2VYdt {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: u64) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &u64 {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> u64 {
        self.0
    }
}
pub enum z2VWBb {z2Vay1 , z2VW3f , z2VTbG ,} 
